### ISSUE TITLE
implement the login screen

### ISSUE THREAD

**Issue by vnmedeiros** [tainacan/tainacan-mobile#23]
In the login screen, need a control to select a Tainacan installation for user to realize a login

**Comment by mateuswetah** [comment]
- [ ] Rename component to `login` or `login-form`;
- [ ] Use `@submit` event on the `<form>` tag;
- [ ] Use `type="submit"` on the `<button>`;
- [ ] Experiment the usage of [`inputmode="url"`](https://ionicframework.com/docs/api/input#inputmode) in the `urlMuseum`;
- [ ] Change `urlMuseum` to `siteUrl` or something like this (avoid the term "museum");
- [ ] Set all three fields as `required="true"`;
