### ISSUE TITLE
Link to access full list of the collections

### ISSUE THREAD

**Issue by vnmedeiros** [tainacan/tainacan-mobile#6]

**Comment by mateuswetah** [comment]
While the collections-list component was created, it should be used here as well. You can see that there is a lot of code repetition happening:

- [ ] Rename `base-collections-list` to `collections-list` - the base thing is really a thing for the layout component;
- [ ] Move the logic of "fetching" the collections from the `collections-list` component to its possible parents (home and full collections list). They should handle this, while the `collections-list` only uses a computed property to see the collections from the store.
- [ ] Also, by doing this, you should use a single function to fetch the collections on the store, and just pass different parameters to it, according to where you are. So you would have something like `this.collectionsStore.fetchCollections({ perpage: 3, orderby: creation })` etc...
- [ ] If you need to inform loading state from the parent components (the pages) to the `collections-list`, remember that you can have a prop to receive the `is-loading` state.

**Comment by mateuswetah** [comment]
Also, all the comments above are valid for the items as well!
